config/routes.rb
Lendshelf::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  resources :users do
    resources :items, except: [:index]
  end

  
  resources :groups
  root 'users#splash'
  

  get 'items/search' => 'items#search_results', as: :search_item

  post 'user/:id/requests/:item_id' => 'users#request_loan', as: :request_loan
  post 'user/:id/approves/:item_id' => 'users#approve_loan', as: :approve_loan
  post 'user/:id/denies/:item_id' => 'users#deny_loan', as: :deny_loan
  post 'user/:id/returns/:item_id' => 'users#return_loan', as: :return_loan

  post 'group/:id/join_group/:user_id' => 'groups#join_group', as: :join_group
  post 'group/:id/leave_group/:user_id' => 'groups#leave_group', as: :leave_group

  post 'group/:id/approve_member/:user_id' => 'groups#approve_member', as: :approve_member
  post 'group/:id/deny_member/:user_id' => 'groups#deny_member', as: :deny_member

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships

  def members
    self.memberships.where.not(:state => 'pending')
  end

  def pending_members
    self.memberships.where(:state => "pending")
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join_group, :leave_group, :approve_member, :deny_member]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
    @available_group_items = []
    @unavailable_group_items = []
    @group.users.includes(:items).each do |user|
      if user != current_user && user.group_membership(@group).state != "pending"
        @available_group_items = @available_group_items + user.items.where(:state => "available")
        @unavailable_group_items = @unavailable_group_items +  user.items.where.not(:state => "available")
      end 
    end
    @members = @group.memberships.where.not(:state => "pending")
    @pending = @group.memberships.where(:state => "pending")
  end


  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def join_group
    @group.memberships.create(:user_id => params[:user_id])
    redirect_to @group, notice: "Your membership request has been submitted"
  end

  def leave_group
    membership = @group.memberships.find_by(:user_id => params[:user_id])
    membership.destroy
    if @group.memberships.size == 0
      @group.destroy
      redirect_to current_user, notice: "You were the last member of that group. It is now gone :( "
    else
      redirect_to @group
    end
  end

  def approve_member
    membership = @group.memberships.find_by(:user_id => params[:user_id])
    membership.approve_member
    redirect_to @group
  end

  def deny_member
    membership = @group.memberships.find_by(:user_id => params[:user_id])
    membership.destroy
    redirect_to @group
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)
    respond_to do |format|
      if @group.save
        @group.memberships.create(user_id: current_user.id, state: "owner")
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    
    <h1>Discover Groups</h1>

    <% current_user.recommend_groups.each do |group| %>
      <div class="group-box">
        <div class="nav group-header">
          <h4 class="navbar-left group-buffer">
            <%= link_to "#{group.name} (#{pluralize(group.members.size, 'member')})", group, :class => "group-link" %>
          </h4>
        </div>
        <span></span>
        <p class="group-buffer">
          <%= group.description %>
        </p>
        <p class="group-buffer">
          You know <% (current_user.grouped_users && group.users).each do |user| %>
              <%= link_to user.name, user %>
            <% end %> in this group.
        </p>
      </div>
      <br>
    <% end %>

  </div>

  <div class="col-md-1"></div>

</div>

app/views/groups/new.html.erb
<h1>New group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h1><strong><%= @group.name %></strong></h1>
</div>



<div class="row">
  <div class="col-md-8">
    <h4><%= @members.size %> Members</h4>
    <p><strong><%= @group.description %></strong></p>
  </div>

  <div class="pull-right" style="padding-right: 10px;">
    <% if current_user != nil %>
      <% if !(current_user.groups.include?(@group)) %>
        <%= button_to 'Request to join this group', join_group_path(@group.id, current_user.id), :class => "btn btn-success btn-sm" %>
      <% else %>
        <%= button_to "#{current_user.group_membership(@group).state == "pending" ? "Withdraw join request" : "Leave this group"}", leave_group_path(@group.id, current_user.id), data: { confirm: "Are you sure? #{'You are the last member. If you leave the group will be disbanded.' if @group.memberships.size == 1}" }, :class => "btn btn-danger btn-sm" %>
      <% end %>
    <% end %>
  </div>
</div>


<div class="tabbable">
  <ul id="myTab" class="nav nav-tabs">
      <li class="active"><a href="#tab1" data-toggle="tab">Members</a></li>
    <% if current_user && current_user.group_member?(@group) %>
      <li class=""><a href="#tab2" data-toggle="tab">Items</a></li>
    <% end %>
    <% if current_user && current_user.group_admin?(@group) %>
      <li class=""><a href="#tab3" data-toggle="tab">Manage</a></li>
    <% end %>
  </ul>
  <div id="myTabContent" class="tab-content">


<!-- BEGINS TAB1 CONTENT -->
    <div class="tab-pane fade active in" id="tab1">

      <ul><% @members.each do |m| %>
          <li><%= link_to m.user.name, m.user %> (<%= pluralize( m.user.items.length, "item") %>)</li>
        <% end %></ul>
    </div>


<!-- BEGINS TAB2 CONTENT -->
    <div class="tab-pane fade" id="tab2">
      <h4 class="margin-top-large">Group Items (Available: <%= @available_group_items.size %>)</h4>
      <table class="table table-striped table-hover table-condensed table-outliner">
        <thead>
          <tr>
            <th>Title</th>
            <th>Type</th>
            <th>Status</th>
            <th>Owner</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @available_group_items.each do |item| %>
            <tr>
              <td><%= link_to item.name, user_item_path(item.user_id, item.id) %></td>
              <td><%= item.type_list.last %></td>
              <td><%= item.state.capitalize %> </td>
              <td><%= item.user.name %></td>
              <td style="width: 80px;"><% if current_user.group_member?(@group) && current_user != item.user %>
                <%= button_to "Request", request_loan_path(current_user, item.id), :class => "btn btn-primary btn-xs" %> 
                <% end %></td>

      <!-- Loops the <td> line so that both buttons fit on one line -->
            </tr>
          <% end %>
        </tbody>
      </table>

      <h4 class="margin-top-large">Group Items (Unavailable Items: <%= @unavailable_group_items.size %>)</h4>
      <table class="table table-striped table-hover table-condensed table-outliner">
        <thead>
          <tr>
            <th>Title</th>
            <th>Type</th>
            <th>Status</th>
            <th>Owner</th>
            <th></th>
        </thead>
        <tbody>
          <% @unavailable_group_items.each do |item| %>
            <tr>
              <td><%= link_to item.name, user_item_path(item.user_id, item.id) %></td>
              <td><%= item.type_list.last %></td>
              <td><%= item.state.capitalize %> </td>
              <td><%= link_to item.user.name, item.user %></td>
              <td style="width: 80px;"><% if current_user == item.loans.last %>
                  <%= button_to "Cancel", deny_loan_path(item.user.id, item.id), class: "btn btn-warning btn-xs btn-inline" %>
                  <% end %></td>
      <!-- Ends loop -->
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>



<!-- BEGINS TAB3 CONTENT -->
    <% if current_user && current_user.group_admin?(@group) %>
    <div class="tab-pane fade" id="tab3">

          <div class="pull-right">
            <%= link_to 'Edit Group', edit_group_path(@group), :class => "btn btn-primary btn-sm" %>
          </div>

          <h4>Pending Members (<%= @pending.size %>):</h4>
          <ul>
            <% @pending.each do |m| %>
              <li>
                <%= link_to m.user.name, m.user %> (<%= pluralize( m.user.items.length, "item") %>)
                <%= button_to "Approve", approve_member_path(@group.id, m.user_id), :class => "pull-left btn btn-success btn-sm signup" %>
                <%= button_to "Deny", deny_member_path(@group.id, m.user_id), :class => "pull-left btn btn-danger btn-sm signup" %>
              </li>
            <% end %>
          </ul>
    </div>
    <% end %>



  </div>
</div>    