config/routes.rb
Lendshelf::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  resources :users do
    resources :items, except: [:index]
  end

  
  resources :groups
  root 'users#splash'
  

  get 'items/search' => 'items#search_results', as: :search_item

  post 'user/:id/requests/:item_id' => 'users#request_loan', as: :request_loan
  post 'user/:id/approves/:item_id' => 'users#approve_loan', as: :approve_loan
  post 'user/:id/denies/:item_id' => 'users#deny_loan', as: :deny_loan
  post 'user/:id/returns/:item_id' => 'users#return_loan', as: :return_loan

  post 'group/:id/join_group/:user_id' => 'groups#join_group', as: :join_group
  post 'group/:id/leave_group/:user_id' => 'groups#leave_group', as: :leave_group

  post 'group/:id/approve_member/:user_id' => 'groups#approve_member', as: :approve_member
  post 'group/:id/deny_member/:user_id' => 'groups#deny_member', as: :deny_member

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :memberships
  has_many :groups, through: :memberships
  has_many :items
  has_many :loans
  has_many :borrowed_items, through: :loans, source: "item"

  # def name
  #   "#{firstname.capitalize} #{lastname.capitalize}"
  # end


  def request_loan(item)
    self.loans.create(:item_id => item.id)
    item.request_event
  end

  def approve_loan(item)
    item.loans.last.update(:borrowed_on => Time.now)
    item.loan_event
  end

  def deny_loan(item)
    item.loans.last.destroy
    item.deny_event
  end

  def return_loan(item)
    item.loans.last.update(:returned_on => Time.now)
    item.return_event
  end


  def my_available_items
    self.items.where(state: "available")
  end

  def my_requested_items
    self.items.where(state: "requested")
  end

  def my_loaned_items
    self.items.where(state: "borrowed")
  end

  def currently_borrowing
    self.loans.where(returned_on: nil).where.not(borrowed_on: nil)
  end

  def currently_requesting
    self.loans.where(borrowed_on: nil)
  end


  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  def group_membership(group)
    self.memberships.where(:group_id => group.id).last
  end

  def group_member?(group)
    self.groups.include?(group) && self.group_membership(group).state != "pending"
  end

  def group_admin?(group)
    self.groups.include?(group) && (self.group_membership(group).state == "admin" || self.group_membership(group).state == "owner")
  end

  def grouped_users
    user_list = []
    self.groups.includes(:users).each do |group|
      group.users.each do |user|
        user_list << user if user != self && !user_list.include?(user)
      end
    end
    user_list
  end

  def recommend_groups
    group_list = []
    self.grouped_users.each do |user|
      user.groups.each do |group|
        group_list << group if !(self.groups.include?(group))
      end
    end
    group_list
  end

  def available_to_borrow
    # Get group ids
    # Get users who belong to groups with those ids
    # Get items of those users
    group_ids = self.groups.collect(&:id)
    item_lists = []
    Group.where("id IN (?)", group_ids).includes(:users).each do |group|
      group.users.each do |user|
        if user != self
          item_lists << user.items
        end
      end
    end
    item_lists.uniq
  end
  
  def search_items(search_string)
    user_item_lists = available_to_borrow
    name_items = user_item_lists.collect do |user_items|
      user_items.where("name like ?", "%#{search_string}%")
    end.flatten

    type_items = user_item_lists.collect do |user_items|
      user_items.tagged_with([search_string], :on => :types, :any => true)
    end.flatten

    tag_items = user_item_lists.collect do |user_items|
      user_items.tagged_with([search_string], :on => :tags, :any => true)
    end.flatten

    all_results = (name_items + type_items + tag_items).uniq
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :approve_loan, :request_loan, :deny_loan, :return_loan]
  before_action :set_item, only: [:approve_loan, :request_loan, :deny_loan, :return_loan]
  skip_before_filter :authenticate_user!, only: [:index, :splash]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def request_loan
    @user.request_loan(@item)
    redirect_to(@user)
  end

  def approve_loan
    @user.approve_loan(@item)
    redirect_to(@user)    
  end

  def deny_loan
    @user.deny_loan(@item)
    redirect_to(@user)
  end

  def return_loan
    @user.return_loan(@item)
    redirect_to(@user)
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def splash
    if current_user
      redirect_to current_user
    else
      render :layout => false
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    def set_item
      @item = Item.find(params[:item_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">
    <h1>User List</h1>
      <p id="notice"> <%= notice%>
      </p>
    <table>
      <thead>
        <tr>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= link_to user.name, user %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-1"></div>
</div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice" style="text-align: center;"><%= notice %></p>

<div class="row">
  <div class="col-md-12">

    <div class="tabbable">
      <ul id="myTab" class="nav nav-tabs">
        <li class="active"><a href="#tab1" data-toggle="tab">
          <% if @user != current_user %><%= @user.name %>'s<% else %>My<% end %> Inventory</a></li>
        <% if @user == current_user %>
        <li class=""><a href="#tab2" data-toggle="tab">My Borrowings</a></li>
        <li class=""><a href="#tab3" data-toggle="tab">My Groups</a></li>
        <% end %>
      </ul>
      <div id="myTabContent" class="tab-content">

<!-- BEGINS TAB1 CONTENT -->
        <div class="tab-pane fade active in" id="tab1">
          <div class="user-header">
            <h4 class="navbar-left"><%= @user.my_requested_items.size %>
              <span class="de-emphasize">REQUESTED &nbsp;&nbsp;&nbsp;</span><%= @user.my_loaned_items.size %>
              <span class="de-emphasize">LENT OUT &nbsp;&nbsp;&nbsp;</span><%= @user.my_available_items.size %>
              <span class="de-emphasize">AVAILABLE &nbsp;&nbsp;&nbsp;</span><%= @user.items.size %>
              <span class="de-emphasize">TOTAL</span></h4>
            <p class="navbar-right">
              <% if @user == current_user %>
                <%= link_to 'Add New Item', new_user_item_path(@user), :class => "btn btn-primary" %>
              <% elsif %>
                <%= @user.currently_borrowing.size %>
                <span class="de-emphasize">BORROWING &nbsp;&nbsp;&nbsp;</span><%= @user.currently_requesting.size %>
                <span class="de-emphasize">WAITING TO GET &nbsp;&nbsp;&nbsp;</span>
              <% end %></p>
            <table class="table table-striped table-hover table-condensed table-outliner">
              <thead>
                <tr>
                  <th>Title</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Other User</th>
                  <th>Date</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <% @user.my_requested_items.each do |item| %>
                  <tr>
                    <td><%= link_to item.name, user_item_path(@user.id, item.id) %></td>
                    <td><%= item.type_list.last %></td>
                    <td>Requested</td>
                    <td><% if current_user == @user || current_user == item.loans.last.user %> <!-- hides names that are not the user's -->
                      by <%= link_to item.loans.last.user.name, user_path(item.loans.last.user) %>
                      <% end %></td>
                    <td>on <%= item.loans.last.created_at.strftime("%h %d") %></td>
            <!-- Loops the <td> line so that both buttons fit on one line -->
                    <% if current_user == @user %>
                      <td style="width: 110px;">
                      <%= button_to "Given", approve_loan_path(@user.id, item.id), class: "btn btn-success btn-xs btn-inline" %>
                      <%= button_to "Deny", deny_loan_path(@user.id, item.id), class: "btn btn-danger btn-xs btn-inline" %>
                    <% elsif current_user == item.loans.last.user %>
                      <td>
                      <%= button_to "Cancel", deny_loan_path(@user.id, item.id), class: "btn btn-warning btn-xs btn-inline" %>
                    <% else %><td>
                    <% end %></td>
            <!-- Ends loop -->
                  </tr>
                <% end %>

                <% @user.my_loaned_items.each do |item| %>
                  <tr>
                    <td><%= link_to item.name, user_item_path(@user.id, item.id) %></td>
                    <td><%= item.type_list.last %></td>
                    <td>Lent out</td>
                    <td><% if current_user == @user || current_user == item.loans.last.user %> <!-- hides names that are not the user's -->
                      to <%= link_to item.loans.last.user.name, item.loans.last.user %>
                      <% end %></td>
                    <td>on <%= item.loans.last.created_at.strftime("%h %d") %></td>
                    <td><% if current_user == @user %>
                      <%= button_to "Returned", return_loan_path(@user.id, item.id), data: { confirm: 'Are you sure? This marks your item as Available again and cannot be undone.' }, class: "btn btn-primary btn-xs btn-inline" %>
                      <% end %></td>
                  </tr>
                <% end %>
                <% @user.my_available_items.each do |item| %>
                  <tr>
                    <td><%= link_to item.name, user_item_path(@user.id, item.id) %></td>
                    <td><%= item.type_list.last %></td>
                    <td>Available</td>
                    <td></td>
                    <td></td>
                    <td><% if current_user && current_user != @user %>
                      <%= button_to "Request", request_loan_path(current_user, item.id), :class => "btn btn-primary btn-xs" %> 
                      <% end %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

          </div>
        </div>              
<!-- ENDS TAB1 CONTENT -->
<!-- BEGIN TAB2 CONTENT -->
        <div class="tab-pane fade" id="tab2">
          <h4><%= @user.currently_borrowing.size %>
            <span class="de-emphasize">BORROWING &nbsp;&nbsp;&nbsp;</span><%= @user.currently_requesting.size %>
            <span class="de-emphasize">WAITING TO GET &nbsp;&nbsp;&nbsp;</span><%= @user.items.size %>
            <span class="de-emphasize">TOTAL</span>
          </h4>

          <table class="table table-striped table-hover table-condensed table-outliner">
            <thead>
              <tr>
                <th>Title</th>
                <th>Type</th>
                <th>Status</th>
                <th>Other User</th>
                <th>Date</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @user.currently_borrowing.each do |loan|%>
                <tr>
                  <td><%= link_to loan.item.name, user_item_path(loan.item.user_id, loan.item_id) %></td>
                  <td><%= loan.item.type_list.last %></td>
                  <td>Borrowing</td>
                  <td>from <%= link_to loan.item.user.name, loan.item.user %></td>
                  <td>since <%= loan.created_at.strftime("%h %d") %></td>
                  <td></td>
                </tr>
              <% end %>
              <% @user.currently_requesting.each do |loan|%>
                <tr>
                  <td><%= link_to loan.item.name, user_item_path(loan.user.id, loan.item.id) %></td>
                  <td><%= loan.item.type_list.last %></td>
                  <td>Waiting to get</td>
                  <td>from <%= link_to loan.item.user.name, user_path(loan.item.user) %></td>
                  <td>since <%= loan.created_at.strftime("%h %d") %></td>
                  <td><% if current_user == @user %>
                    <%= button_to "Cancel", deny_loan_path(loan.user.id, loan.item.id), class: "btn btn-warning btn-xs btn-inline" %>
                    <% end %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
<!-- ENDS TAB2 CONTENT -->
<!-- BEGIN TAB3 CONTENT -->
        <div class="tab-pane fade" id="tab3">
          <div class="user-header">
            <h4 class="navbar-left"><%= @user.groups.size %>
              <span class="de-emphasize">TOTAL GROUP MEMBERSHIPS</span></h4>
            <p class="navbar-right">
              <%= link_to 'New Group', new_group_path, :class => "btn btn-primary" %></p>

          <table class="table table-striped table-hover table-condensed table-outliner">
            <thead>
              <tr>
                <th>Name</th>
                <th>Description</th>
                <th>Members</th>
                <th>Items</th>
                <th>Your Status</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @user.groups.each do |group|%>
                <tr>
                  <td><%= link_to group.name, group %></td>
                  <td><%= group.description %></td>
                  <td><%= group.members.size %></td>
                  <td><%= group.members.inject(0) {|i, m| i + (m.user.items.size) } %></td>
                  <td><%= @user.group_membership(group).state.titleize %></td>
                  <td><%= link_to("Edit Group", edit_group_path(group)) if @user.group_membership(group).state == "owner" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
<!-- ENDS TAB3 CONTENT -->
      </div>
    </div>
  </div>
</div>

app/views/users/splash.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lendshelf</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <!--Change order for full width navbar
  <div class="navbar"> 
    <div class="container" data-toggle="clingify">-->
  <div class="container" data-toggle="clingify">
    <div class="navbar">   
        <!--
      mobile collapse menu button
      - data-toggle="toggle" = default BS menu
      - data-toggle="jpanel-menu" = jPanel Menu
      --> 
      
      <!--user menu-->
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbo-padder"></div>
    <div class="jumbotron jumbo-picture">
      <div class="container">
        <h1 class="jumbo-text">Lendshelf</h1>
        <p>Lendshelf is a social lending app that helps you share what you love with your friends, coworkers, and relatives.</p>
        <p><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", class: "btn btn-primary btn-lg signup" %></p>
      </div>
    </div>

    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>First steps</h2>
          <p>Using Lendshelf is simple! Just make or join a group and list some items. Anyone who shares a group with you can see what you have available and request to borrow it. </p>
          <!-- <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p> -->
        </div>
        <div class="col-md-4">
          <h2>The exchange</h2>
          <p>When one of your friends wants to borrow something from you the request appears on your profile page. Once you've handed him the item you simply mark it as Given. When your friend returns it you mark it as returned and it becomes available for others to request.</p>
          <!-- <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p> -->
       </div>
        <div class="col-md-4">
          <h2>Who has that?</h2>
          <p>You'll never have to worry about who has what again. Lendshelf keeps a full history of each of your items, so you can see when it was borrowed and returned.</p>
          <!-- <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p> -->
        </div>
      </div>

      <hr>

      <footer>
        <p>&copy; James Tong, Sam Yang, & Josh Scaglione - Team Tigon @flatiron 2013</p>
      </footer>
    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>

  </body>
</html>