config/routes.rb
Lendshelf::Application.routes.draw do
  get "sessions/create"
  get "sessions/destroy"
  resources :users do
    resources :items, except: [:index]
  end

  
  resources :groups
  root 'users#splash'
  

  get 'items/search' => 'items#search_results', as: :search_item

  post 'user/:id/requests/:item_id' => 'users#request_loan', as: :request_loan
  post 'user/:id/approves/:item_id' => 'users#approve_loan', as: :approve_loan
  post 'user/:id/denies/:item_id' => 'users#deny_loan', as: :deny_loan
  post 'user/:id/returns/:item_id' => 'users#return_loan', as: :return_loan

  post 'group/:id/join_group/:user_id' => 'groups#join_group', as: :join_group
  post 'group/:id/leave_group/:user_id' => 'groups#leave_group', as: :leave_group

  post 'group/:id/approve_member/:user_id' => 'groups#approve_member', as: :approve_member
  post 'group/:id/deny_member/:user_id' => 'groups#deny_member', as: :deny_member

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many :loans
  has_many :borrowers, through: :loans, source: "user"

  acts_as_taggable_on :tags, :types

  state_machine :initial => :available do

    event :request_event do
      transition :available => :requested
    end

    event :deny_event do
      transition :requested => :available
    end

    event :loan_event do
      transition :requested => :borrowed
    end

    event :return_event do
      transition :borrowed => :available
    end

  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_user, only: [:index, :show, :new, :edit, :update, :destroy]
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.where(:user_id => params[:user_id])
  end

  def show
  end

  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    if current_user == @user
      render action: "edit"
    else
      redirect_to [@user, @item], notice: "You cannot edit items that do not belong to you"
    end
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.user_id = params[:user_id]
#how do u require the user_id in the item_params (look into it later)
    respond_to do |format|
      if @item.save
        format.html { redirect_to user_path(@item.user_id), notice: 'item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item = @user.items.find(params[:id])

    @item.update(:type_list => "", :tag_list => "")
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to [@user, @item], notice: 'item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end


  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item = @user.items.find(params[:id])
    @item.destroy


    respond_to do |format|
      format.html { redirect_to user_items_path(@user) }
      format.json { head :no_content }
    end
  end


  def search_results
    @results =  current_user.search_items(params[:search_string])
    render action: 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def set_user
      @user = User.find_by(id: params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :tag_list, :type_list, :description)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for([current_user, @item]) do |f| %> 
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.label :name %><br>
    <%= f.text_field :name, :required => true %><br>

    <%= f.select(:type_list, options_for_select([['Book'], ['Movie, DVD'], ['Movie, Blu-Ray'], ['Music, CD'], ['Video Game'], ['Tabletop Game'], ['Sporting Goods'], ['Toys'], ['Tools'], ['Electronics']])) %>
    <br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
    <%= f.label :tag_list, "Enter tags, separated by commas" %><br>
    <%= f.text_area :tag_list %><br>
    <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing '<%= @item.name %>'</h1>

<%= render 'form' %>

<%= link_to 'Cancel Edit', user_item_path(@item.user_id,@item) %> |
<%= link_to 'Back to User', user_path(@item.user_id) %>

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-2"></div>
  <div class="col-md-8">

    <table class="table table-striped table-hover table-condensed">
    <thead>
      <tr>
        <th>
          Search Results:
        </th>
      </tr>
    </thead>
    <% @results.each do |item| %>
      <tbody>
      <tr>
        <td>
          <%= link_to "#{item.name} - #{item.type_list.join(", ")}", user_item_path(item.user_id, item.id) %>

          <%= link_to "Owned by #{item.user.name}", item.user, :class => "pull-right" %>
          <br>
          Tags: <%= item.tag_list.length > 0 ? item.tag_list : "none" %>
        </td>
      </tr>
      </tbody>
    <% end %>
    </table>

    <br>

  </div>
  <div class="col-md-2"></div>
</div>



  <thead>
    <tr>
      <th></th>
    </tr>
  </thead>

  <tbody>

app/views/items/new.html.erb
<h1>New item</h1>

<%= render 'form' %>

<%= link_to 'Cancel', user_path(@user) %>

app/views/items/show.html.erb
<div class="row">
  <div class="col-md-1"></div>
  <div class="col-md-10">

    <p id="notice"><%= notice %></p>
    <h3><%= @item.name %> - <span class="de-emphasize"><%= @item.type_list %></span></h3>
         
          <% if @item.user.name == current_user.name %> 
            <div><i>Owned by You<i> </div>
          <% else %>
            <div><i>Owned by <%= @item.user.name %> </i></div>
          <% end %>
       <br>
    <h4>Tags:</h4>
    <div><%= @item.tag_list %></div><br>



    <h4>  Description:      </h4>
    <div><%= @item.description  %></div></br>
  <h4> History: </h4>
    <% @item.loans.each do |loan| %>
      <ol>
        <% if loan.borrowed_on %>
          <li><%= "Borrowed by #{loan.user.name} on #{loan.borrowed_on.strftime("%h %d")}" %></li>
        <% end %>
        <% if loan.returned_on %>
          <li><%= "Returned by #{loan.user.name} on #{loan.returned_on.strftime("%h %d")}" %></li>
        <% end %>
      </ol>
    <% end %>
    <br>
    <% if current_user && current_user != @user && @item.available? %>
        <%= button_to "Request to Borrow", request_loan_path(current_user, @item.id), :class => "btn btn-primary btn-sm" %> 
    <% end %>
    <br>
    <% if current_user == @user %>
      <%= link_to 'Edit', edit_user_item_path(@user, @item) %> |
    <% end %>
    <%= link_to 'Back', user_path(@user) %>
     
  </div>
  <div class="col-md-1"></div>
</div>